# Generated by Django 4.2.1 on 2023-06-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
